### ISSUE TITLE
Element model does not appear in device with master/release mode

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MRDesignLabs_Unity_PeriodicTable#1]
In the detail view, element model does not appear in device with master/release mode build.
It only shows up in the device when you deploy with the debug mode.

![2017-05-08 12_43_55-unity 5 6 0f3 personal 64bit - main unity - mrdesignlabs_unity_periodictable -](https://cloud.githubusercontent.com/assets/13754172/25822039/334a63f2-33ec-11e7-9f06-400f0b759f94.png)

**Comment by rpatel-scale** [comment]
I am facing a similar issue. The element model doesn't show up on release nor debug for me. It only shows up on hololens 2 emulator...
